defaults:
  - data: wnut17
  - model: distilroberta_ner
  - trainer: default
  - _self_
  - experiment: source_only

seed: 1

paths:
  output_root: outputs
  output_dir: ${paths.output_root}/${experiment.name}_shots_${experiment.shot_count}_norm_${experiment.do_normalization}_selftrain_${experiment.do_self_training}/seed_${seed}

experiment:
  shot_count: 100
  do_finetune: true
  do_normalization: false
  do_self_training: false
  pseudo_label_threshold: 0.95
  self_training_epochs: 2

clearml:
  project_name: nlp-course-ner-domain-adaptation
  task_name: ${experiment.name}_shots_${experiment.shot_count}_norm_${experiment.do_normalization}_selftrain_${experiment.do_self_training}_seed_${seed}
  offline_mode: false

normalization:
  normalize_usernames: true
  normalize_urls: true
  collapse_repeated_chars: true
  repeated_char_min_repeats: 3
  repeated_char_keep: 2
  normalize_hashtags: false

error_analysis:
  max_error_rows: 1000
  rare_token_threshold: 1

hydra:
  run:
    dir: ${paths.output_dir}
  job:
    chdir: false
